### ISSUE TITLE
Opening a profile that’s already open doesn’t do anything on macOS

### ISSUE THREAD

**Issue by MattHardcastle** [null-dev/firefox-profile-switcher-connector#2]
To recreate:
1) use Firefox profile switcher to open another profile,
2) then attempt to open the profile from the original Firefox window.

What happens:
The second attempt will focus above all windows except the current Firefox window which will still have focus.

What I wish would happen:
The Firefox window with the profile I'm attempting to open will steal focus from the current profile.

**Comment by null-dev** [comment]
I'm seeing this issue on Windows too and I'm still looking into it. The extension currently uses the browser's built in "focus" functionality: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/update. E.g. It runs:

```js
browser.windows.update({windowId, focused: true})
```

The browser "focuses" the window but it does not bring the window to the top. This could be a bug on Firefox's end and if it is it will be a big pain to workaround.

**Comment by null-dev** [comment]
I've implemented a workaround in the newest connector version (v0.0.8) so this should be solved now! You also need to the latest extension version and you have to enable "Window focus workaround" in the extension settings.
