### ISSUE TITLE
BitDefender detects v0.0.8 of firefox-profile-switcher-connector.exe as RAZY malware.

### ISSUE THREAD

**Issue by doublehelix** [null-dev/firefox-profile-switcher-connector#7]
Probably a false-positive given the lower than usual hit-rate, but BitDefender (and at least one other engine) is flagging (and quarantining) v0.0.8 of the `firefox-profile-switcher-connector.exe` as a virus.

**_OS:_** Windows 11 Ent. (v10.0.220000)

Worth looking into the reason for the detection and flagging it with BitDefender as a false positive if so?
https://www.bitdefender.com/submit

Unfortunately I don't have enough Rust experience to assist on this one.

```
The file C:\Users\Username\AppData\Local\FirefoxProfileSwitcher\native-connector\firefox-profile-switcher-connector.exe is infected with Gen:Variant.Razy.985422 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.
```

![image](https://user-images.githubusercontent.com/355130/139967743-e7070c1f-2a6a-412f-ad75-1640a8e747c6.png)

![image](https://user-images.githubusercontent.com/355130/139968438-39f779d6-85fd-459d-a603-4115dcc76f74.png)

**Comment by Da-Boom** [comment]
Might want to try re-scanning it - I just scanned with VirusTotal... and it went up from 6 detections on a previous scan to 11... makes me a little worried, given that Razy works by installing a malicious browser extension... - until our friend null-dev responds with a through in dept reasoning as to why its a false positive (also why it needs to access the windows cryptography store and direct cpu clock access - according to virustotal) 

Here is the scan that i performed - check behavior, it will confirm that this file is the file its what it is (it has the windows installer prompts under the highlighted actions heading)

https://www.virustotal.com/gui/file/4f6c549a406726f12146bbe47b20e246d41c816d094dd5adbe2b466ee66e2d11/detection

Not saying it isn't a false positive... not saying it is either... I don't have any experience in rust so looking through the code doesn't really help me. Ntm for all we know the release binary could be different to the compiled binary - its possible someone could've hijacked it, injecting razy (can someone confirm by building it and doing a scan? - i don't have a dev environment set up for windows, and seen as that's the one we are looking at here, it seems prudent to run some tests on that platform)

**Comment by null-dev** [comment]
The extension is probably getting mis-identified because when you create a new browser profile using it, it installs itself in the new profile.

I will submit it as a false positive to bitdefender.

Mentioning the other issue here so I can close it once I get this resolved: https://github.com/null-dev/firefox-profile-switcher/issues/17

**Comment by null-dev** [comment]
I just made a new release to fix an unrelated bug but after uploading it to VirusTotal it's now marked as clean so I'm going to assume this was just a one-off issue. If it's still being detected as malware for you, please re-open the issue.
